### ISSUE TITLE
Requirements installation error

### ISSUE THREAD

**Issue by asif-mahmud-am** [UIC-Liu-Lab/ContinualLM#3]
![image](https://github.com/UIC-Liu-Lab/ContinualLM/assets/65419625/55aee9e4-e2f9-491b-9d5c-f9ca25b60722)

Please check the requirements.txt file. Cannot install the requirements !!

**Comment by 2proveit** [comment]
this link may help you [https://stackoverflow.com/questions/41274007/anaconda-export-environment-file](https://stackoverflow.com/questions/41274007/anaconda-export-environment-file)
