### ISSUE TITLE
Ckpt public time

### ISSUE THREAD

**Issue by rattlesnakey** [UIC-Liu-Lab/ContinualLM#5]
When will the ckpt and the impt_vectors be public ?

**Comment by ZixuanKe** [comment]
Thank you so much for your interest! I hope it's not too late, but we have uploaded our checkpoints at[ https://github.com/UIC-Liu-Lab/ContinualLM#checkpoints-in-huggingface](https://github.com/UIC-Liu-Lab/ContinualLM#checkpoints-in-huggingface). Please feel free to play with it!
