### ISSUE TITLE
question about virtual parameter

### ISSUE THREAD

**Issue by fancyerii** [UIC-Liu-Lab/ContinualLM#6]
I have a question about virtual parameter. In your paper, 
![图片](https://github.com/UIC-Liu-Lab/ContinualLM/assets/5372812/f0d25b7f-1027-428d-b75f-47d1c957ff17)
![图片](https://github.com/UIC-Liu-Lab/ContinualLM/assets/5372812/10258ff4-3bef-488b-9ab2-8d003cfdb529)

By chain rule,∂L/∂g_l = (∂L/∂^o_l)  x (∂^o_l/∂g_l)=  (∂L/∂^o_l) x (o_l) . So we can just view  g_l as ∂L/∂o_l times  o_l. Am I right?

**Comment by ZixuanKe** [comment]
Thank you so much for your interest. It looks good to me. If you are interested in how we implement that in general, feel free to check our example notebook at[ https://github.com/UIC-Liu-Lab/ContinualLM/blob/main/continual_pretrain.ipynb](https://github.com/UIC-Liu-Lab/ContinualLM/blob/main/continual_pretrain.ipynb).
