### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'location_key'

### ISSUE THREAD

**Issue by VietHoang1512** [UIC-Liu-Lab/ContinualLM#8]
```
    self.self = RobertaSelfAttention(
TypeError: __init__() got an unexpected keyword argument 'location_key'
```

Hi, thank you sharing your great work. However, I encountered this error when trying to run your code. I have also checked the transformer version 4.17 and the `RobertaSelfAttention` does not have this property either.

**Comment by ZixuanKe** [comment]
Thank you so much for your interest! Could you ensure that you have installed both packages?

> ⚠️ Our model is based on transformers==4.17.0 and adapter-transformers==3.0.1. We recommend using these specific versions, as using other versions may result in unexpected bugs.

**Comment by VietHoang1512** [comment]
Yes, I followed your instructions and also checked their release [here](https://github.com/huggingface/transformers/releases/tag/v4.17.0).  But the `RobertaSelfAttention` seems not have this property. Could you please confirm?

**Comment by ZixuanKe** [comment]
Thank you! Please note that installing adapter-transformers will overwrite some files in the transformers package (which may add some properies). Hence, it's crucial to ensure you have installed both, ideally installing transformers first and then adapter-transformers to ensure a smooth overwrite process. In fact, this property is in the adapter-transformers package, as demonstrated here: [adapter-transformers release](https://github.com/adapter-hub/adapters/blob/514bff83dfb5e9fdd11fc0cec6a5e75b65ab786e/src/transformers/models/roberta/modeling_roberta.py/#L163)

**Comment by VietHoang1512** [comment]
Fixed my version conflict. Thank you for your support!
